#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ_TO_SQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Train_TicketBooking")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTrain_detail(Train_detail instance);
    partial void UpdateTrain_detail(Train_detail instance);
    partial void DeleteTrain_detail(Train_detail instance);
    partial void Insertpassanger_detail(passanger_detail instance);
    partial void Updatepassanger_detail(passanger_detail instance);
    partial void Deletepassanger_detail(passanger_detail instance);
    partial void Insertbooking_deatil(booking_deatil instance);
    partial void Updatebooking_deatil(booking_deatil instance);
    partial void Deletebooking_deatil(booking_deatil instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}



        public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

        public DataClasses1DataContext()
        {
        }

        public System.Data.Linq.Table<Train_detail> Train_details
		{
			get
			{
				return this.GetTable<Train_detail>();
			}
		}
		
		public System.Data.Linq.Table<passanger_detail> passanger_details
		{
			get
			{
				return this.GetTable<passanger_detail>();
			}
		}
		
		public System.Data.Linq.Table<Seat> Seats
		{
			get
			{
				return this.GetTable<Seat>();
			}
		}
		
		public System.Data.Linq.Table<booking_deatil> booking_deatils
		{
			get
			{
				return this.GetTable<booking_deatil>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Train_details")]
	public partial class Train_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _train_id;
		
		private string _train_name;
		
		private string _Sources;
		
		private string _Distination;
		
		private EntitySet<booking_deatil> _booking_deatils;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontrain_idChanging(int value);
    partial void Ontrain_idChanged();
    partial void Ontrain_nameChanging(string value);
    partial void Ontrain_nameChanged();
    partial void OnSourcesChanging(string value);
    partial void OnSourcesChanged();
    partial void OnDistinationChanging(string value);
    partial void OnDistinationChanged();
    #endregion
		
		public Train_detail()
		{
			this._booking_deatils = new EntitySet<booking_deatil>(new Action<booking_deatil>(this.attach_booking_deatils), new Action<booking_deatil>(this.detach_booking_deatils));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_train_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int train_id
		{
			get
			{
				return this._train_id;
			}
			set
			{
				if ((this._train_id != value))
				{
					this.Ontrain_idChanging(value);
					this.SendPropertyChanging();
					this._train_id = value;
					this.SendPropertyChanged("train_id");
					this.Ontrain_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_train_name", DbType="NVarChar(20)")]
		public string train_name
		{
			get
			{
				return this._train_name;
			}
			set
			{
				if ((this._train_name != value))
				{
					this.Ontrain_nameChanging(value);
					this.SendPropertyChanging();
					this._train_name = value;
					this.SendPropertyChanged("train_name");
					this.Ontrain_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sources", DbType="NVarChar(20)")]
		public string Sources
		{
			get
			{
				return this._Sources;
			}
			set
			{
				if ((this._Sources != value))
				{
					this.OnSourcesChanging(value);
					this.SendPropertyChanging();
					this._Sources = value;
					this.SendPropertyChanged("Sources");
					this.OnSourcesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distination", DbType="NVarChar(20)")]
		public string Distination
		{
			get
			{
				return this._Distination;
			}
			set
			{
				if ((this._Distination != value))
				{
					this.OnDistinationChanging(value);
					this.SendPropertyChanging();
					this._Distination = value;
					this.SendPropertyChanged("Distination");
					this.OnDistinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Train_detail_booking_deatil", Storage="_booking_deatils", ThisKey="train_id", OtherKey="train_id")]
		public EntitySet<booking_deatil> booking_deatils
		{
			get
			{
				return this._booking_deatils;
			}
			set
			{
				this._booking_deatils.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_booking_deatils(booking_deatil entity)
		{
			this.SendPropertyChanging();
			entity.Train_detail = this;
		}
		
		private void detach_booking_deatils(booking_deatil entity)
		{
			this.SendPropertyChanging();
			entity.Train_detail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.passanger_details")]
	public partial class passanger_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pass_id;
		
		private string _passanger_name;
		
		private System.Nullable<long> _mobile_no;
		
		private EntitySet<booking_deatil> _booking_deatils;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpass_idChanging(int value);
    partial void Onpass_idChanged();
    partial void Onpassanger_nameChanging(string value);
    partial void Onpassanger_nameChanged();
    partial void Onmobile_noChanging(System.Nullable<long> value);
    partial void Onmobile_noChanged();
    #endregion
		
		public passanger_detail()
		{
			this._booking_deatils = new EntitySet<booking_deatil>(new Action<booking_deatil>(this.attach_booking_deatils), new Action<booking_deatil>(this.detach_booking_deatils));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pass_id
		{
			get
			{
				return this._pass_id;
			}
			set
			{
				if ((this._pass_id != value))
				{
					this.Onpass_idChanging(value);
					this.SendPropertyChanging();
					this._pass_id = value;
					this.SendPropertyChanged("pass_id");
					this.Onpass_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passanger_name", DbType="NVarChar(20)")]
		public string passanger_name
		{
			get
			{
				return this._passanger_name;
			}
			set
			{
				if ((this._passanger_name != value))
				{
					this.Onpassanger_nameChanging(value);
					this.SendPropertyChanging();
					this._passanger_name = value;
					this.SendPropertyChanged("passanger_name");
					this.Onpassanger_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile_no", DbType="BigInt")]
		public System.Nullable<long> mobile_no
		{
			get
			{
				return this._mobile_no;
			}
			set
			{
				if ((this._mobile_no != value))
				{
					this.Onmobile_noChanging(value);
					this.SendPropertyChanging();
					this._mobile_no = value;
					this.SendPropertyChanged("mobile_no");
					this.Onmobile_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="passanger_detail_booking_deatil", Storage="_booking_deatils", ThisKey="pass_id", OtherKey="pass_id")]
		public EntitySet<booking_deatil> booking_deatils
		{
			get
			{
				return this._booking_deatils;
			}
			set
			{
				this._booking_deatils.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_booking_deatils(booking_deatil entity)
		{
			this.SendPropertyChanging();
			entity.passanger_detail = this;
		}
		
		private void detach_booking_deatils(booking_deatil entity)
		{
			this.SendPropertyChanging();
			entity.passanger_detail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seats")]
	public partial class Seat
	{
		
		private System.Nullable<int> _train_id;
		
		private string _Compartment_type;
		
		private string _Compartment_count;
		
		private System.Nullable<int> _Total_SeatCount;
		
		public Seat()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_train_id", DbType="Int")]
		public System.Nullable<int> train_id
		{
			get
			{
				return this._train_id;
			}
			set
			{
				if ((this._train_id != value))
				{
					this._train_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Compartment_type", DbType="NVarChar(20)")]
		public string Compartment_type
		{
			get
			{
				return this._Compartment_type;
			}
			set
			{
				if ((this._Compartment_type != value))
				{
					this._Compartment_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Compartment_count", DbType="NVarChar(20)")]
		public string Compartment_count
		{
			get
			{
				return this._Compartment_count;
			}
			set
			{
				if ((this._Compartment_count != value))
				{
					this._Compartment_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_SeatCount", DbType="Int")]
		public System.Nullable<int> Total_SeatCount
		{
			get
			{
				return this._Total_SeatCount;
			}
			set
			{
				if ((this._Total_SeatCount != value))
				{
					this._Total_SeatCount = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.booking_deatils")]
	public partial class booking_deatil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ticket_id;
		
		private System.Nullable<int> _train_id;
		
		private string _compartment_type;
		
		private System.Nullable<int> _pass_id;
		
		private string _T_date;
		
		private System.Nullable<int> _seat_no;
		
		private EntityRef<Train_detail> _Train_detail;
		
		private EntityRef<passanger_detail> _passanger_detail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTicket_idChanging(int value);
    partial void OnTicket_idChanged();
    partial void Ontrain_idChanging(System.Nullable<int> value);
    partial void Ontrain_idChanged();
    partial void Oncompartment_typeChanging(string value);
    partial void Oncompartment_typeChanged();
    partial void Onpass_idChanging(System.Nullable<int> value);
    partial void Onpass_idChanged();
    partial void OnT_dateChanging(string value);
    partial void OnT_dateChanged();
    partial void Onseat_noChanging(System.Nullable<int> value);
    partial void Onseat_noChanged();
    #endregion
		
		public booking_deatil()
		{
			this._Train_detail = default(EntityRef<Train_detail>);
			this._passanger_detail = default(EntityRef<passanger_detail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticket_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ticket_id
		{
			get
			{
				return this._Ticket_id;
			}
			set
			{
				if ((this._Ticket_id != value))
				{
					this.OnTicket_idChanging(value);
					this.SendPropertyChanging();
					this._Ticket_id = value;
					this.SendPropertyChanged("Ticket_id");
					this.OnTicket_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_train_id", DbType="Int")]
		public System.Nullable<int> train_id
		{
			get
			{
				return this._train_id;
			}
			set
			{
				if ((this._train_id != value))
				{
					if (this._Train_detail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontrain_idChanging(value);
					this.SendPropertyChanging();
					this._train_id = value;
					this.SendPropertyChanged("train_id");
					this.Ontrain_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compartment_type", DbType="NVarChar(20)")]
		public string compartment_type
		{
			get
			{
				return this._compartment_type;
			}
			set
			{
				if ((this._compartment_type != value))
				{
					this.Oncompartment_typeChanging(value);
					this.SendPropertyChanging();
					this._compartment_type = value;
					this.SendPropertyChanged("compartment_type");
					this.Oncompartment_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass_id", DbType="Int")]
		public System.Nullable<int> pass_id
		{
			get
			{
				return this._pass_id;
			}
			set
			{
				if ((this._pass_id != value))
				{
					if (this._passanger_detail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpass_idChanging(value);
					this.SendPropertyChanging();
					this._pass_id = value;
					this.SendPropertyChanged("pass_id");
					this.Onpass_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_date", DbType="VarChar(10)")]
		public string T_date
		{
			get
			{
				return this._T_date;
			}
			set
			{
				if ((this._T_date != value))
				{
					this.OnT_dateChanging(value);
					this.SendPropertyChanging();
					this._T_date = value;
					this.SendPropertyChanged("T_date");
					this.OnT_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seat_no", DbType="Int")]
		public System.Nullable<int> seat_no
		{
			get
			{
				return this._seat_no;
			}
			set
			{
				if ((this._seat_no != value))
				{
					this.Onseat_noChanging(value);
					this.SendPropertyChanging();
					this._seat_no = value;
					this.SendPropertyChanged("seat_no");
					this.Onseat_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Train_detail_booking_deatil", Storage="_Train_detail", ThisKey="train_id", OtherKey="train_id", IsForeignKey=true)]
		public Train_detail Train_detail
		{
			get
			{
				return this._Train_detail.Entity;
			}
			set
			{
				Train_detail previousValue = this._Train_detail.Entity;
				if (((previousValue != value) 
							|| (this._Train_detail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Train_detail.Entity = null;
						previousValue.booking_deatils.Remove(this);
					}
					this._Train_detail.Entity = value;
					if ((value != null))
					{
						value.booking_deatils.Add(this);
						this._train_id = value.train_id;
					}
					else
					{
						this._train_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Train_detail");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="passanger_detail_booking_deatil", Storage="_passanger_detail", ThisKey="pass_id", OtherKey="pass_id", IsForeignKey=true)]
		public passanger_detail passanger_detail
		{
			get
			{
				return this._passanger_detail.Entity;
			}
			set
			{
				passanger_detail previousValue = this._passanger_detail.Entity;
				if (((previousValue != value) 
							|| (this._passanger_detail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._passanger_detail.Entity = null;
						previousValue.booking_deatils.Remove(this);
					}
					this._passanger_detail.Entity = value;
					if ((value != null))
					{
						value.booking_deatils.Add(this);
						this._pass_id = value.pass_id;
					}
					else
					{
						this._pass_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("passanger_detail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
